import type { Product } from './types';

export const products: Product[] = [
  {
    id: 1,
    name: 'زيت الأرغان المغربي الأصلي',
    description: 'زيت طبيعي 100% للشعر والبشرة، غني بفيتامين E ومضادات الأكسدة.',
    image: 'product-1',
    price: 350,
    discountPrice: 299,
    category: 'زيوت الشعر',
  },
  {
    id: 2,
    name: 'زيت الجوجوبا الذهبي',
    description: 'يرطب البشرة بعمق ويوازن إنتاج الزيوت الطبيعية. مثالي لجميع أنواع البشرة.',
    image: 'product-2',
    price: 280,
    category: 'زيوت البشرة',
  },
  {
    id: 3,
    name: 'زيت الخروع النقي',
    description: 'يعزز نمو الشعر والرموش ويقويها. مستخلص ومعصور على البارد.',
    image: 'product-3',
    price: 150,
    discountPrice: 120,
    category: 'زيوت الشعر',
  },
  {
    id: 4,
    name: 'زيت اللافندر العطري',
    description: 'يساعد على الاسترخاء والنوم العميق. يمكن استخدامه في الفواحات أو للتدليك.',
    image: 'product-4',
    price: 220,
    category: 'زيوت عطرية',
  },
  {
    id: 5,
    name: 'زيت جوز الهند البكر',
    description: 'مرطب فائق للشعر الجاف والبشرة. عضوي ومعتمد.',
    image: 'product-5',
    price: 180,
    discountPrice: 165,
    category: 'زيوت الشعر',
  },
  {
    id: 6,
    name: 'زيت اللوز الحلو',
    description: 'غني بالفيتامينات والمعادن لتغذية البشرة وتفتيحها.',
    image: 'product-6',
    price: 190,
    category: 'زيوت البشرة',
  },
  {
    id: 7,
    name: 'زيت الزيتون الفلسطيني',
    description: 'زيت بكر ممتاز من أجود أشجار الزيتون، مثالي للغذاء والعناية.',
    image: 'product-7',
    price: 400,
    discountPrice: 375,
    category: 'زيوت عامة',
  },
  {
    id: 8,
    name: 'زيت شجرة الشاي',
    description: 'مضاد طبيعي للبكتيريا والفطريات، فعال لعلاج حب الشباب.',
    image: 'product-8',
    price: 250,
    category: 'زيوت البشرة',
  },
];
